name: Dappled Things
favicon: null
layout_spectrum: 0.3549109
typography_spectrum: 0.443959
title: Dappled Things
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d3cfc3'
    - '#ad939c'
    - '#31450a'
    - '#607031'
    - '#a36278'
  brandStrength: 0.02106099
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
