layout_spectrum: 0.3549109
typography_spectrum: 0.443959
color:
  saturation: 0.1916469
  lightness: 0.2601809
  brandStrength: 0.02106099
  rhythmicContrast: 0.3190577
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Dappled Things
