analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.3549109
title: Dappled Things
cta:
  bucket: null
  version: null
  domain: null
color:
  saturation: 0.5
  brandStrength: 0.02106099
  rhythmicContrast: 0
  brandColors:
    - '#d3cfc3'
    - '#ad939c'
    - '#31450a'
    - '#607031'
    - '#a36278'
  lightness: 0.5
purpose: []
favicon: null
name: Dappled Things
typography_spectrum: 0.443959
